tools:
  php_code_sniffer:
    config:
      standard: Drupal
    extensions:
      - module
      - inc
      - install
      - test
      - profile
      - theme
  js_hint:
    use_native_config: true

filter:
    excluded_paths:
        - modules/fbs/prancer/*
        - modules/fbs/vendor/*
